---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#


- block:
    # Validate this first so we don't try to build and push knowing that it
    # will fail
    - name: Validate that Docker Hub configuration file is present
      stat:
        path: "{{ docker_config }}/config.json"
      register: docker_stat

    - name: Fail if configuration directory does not exist
      fail:
        msg: >-
         The file {{ docker_config }}/config.json is expected to be present and
         contain Docker Hub authentication information.
         This file is generated automatically with the command "docker login".
      when: not docker_stat.stat.exists
  when: kolla_push
  tags:
    - setup
    - push

- include: repositories.yml
  tags:
    - build
    - push
- include: docker.yml
  tags:
    - setup

- include: kolla.yml
  tags:
    - setup
    - build
    - push

- name: Record relevant variables with ARA
  ara_record:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    type: "{{ item.type |default('text') }}"
  with_items:
    - { key: "kolla_version", value: "{{ kolla_version }}" }
    - { key: "kolla_git_revision", value: "{{ kolla_git_revision.stdout }}" }
    - { key: "version_hash", value: "{{ version_hash }}" }
    - { key: "trunk_repository", value: "{{ trunk_repository }}", type: "url" }
    - { key: "trunk_deps_repository", value: "{{ trunk_deps_repository }}", type: "url" }
    - { key: "build_id", value: "{{ build_id }}" }
    - { key: "kolla_rdo_images", value: "{{ kolla_rdo_images }}" }
  ignore_errors: "yes"
  tags:
    - setup
    - build
    - push

- name: Build images
  vars:
    image: "{{ item }}"
  include: build.yml
  with_items: "{{ kolla_rdo_images }}"
  when: kolla_build
  tags:
    - build

- block:
    # This is a bit weird due to the docker images format syntax clashing with jinja
    # https://docs.docker.com/engine/reference/commandline/images/#/formatting
    - name: Retrieve list of built images
      shell: >
        docker images {{ kolla_namespace }}/centos-binary* \
          --format "{{ '{{' }}.Repository{{ '}}' }}" \
          --filter "label=build_id={{ build_id }}"
      register: built_images

    - name: Tag images with version and push
      vars:
        image: "{{ item }}"
      include: push.yml
      with_items: "{{ built_images.stdout_lines }}"
  when: kolla_push
  tags:
    - push
