---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

- block:
    - name: "Push images: {{ images | join(', ') }} ({{ kolla_tag }})"
      command: docker push {{ image }}:{{ kolla_tag }}
      async: 900
      poll: 0
      with_items: "{{ images }}"
      loop_control:
        loop_var: "image"
      register: async_results

    - name: Wait for the image batch push to finish
      async_status:
        jid: "{{ async_result_item.ansible_job_id }}"
      with_items: "{{ async_results.results }}"
      loop_control:
        loop_var: "async_result_item"
      register: async_poll_results
      until: async_poll_results.finished
      retries: 30
      delay: 30

    # Doing tag and push in the same task for the sake of doing less tasks
    - name: "docker push {{ image }}:{{ version_hash }}"
      command: >
        {{ item }}
      with_items:
        - "docker tag {{ image }}:{{ kolla_tag }} {{ image }}:{{ version_hash }}"
        - "docker push {{ image }}:{{ version_hash }}"
  environment:
    DOCKER_CONFIG: "{{ docker_config }}"
